CREATE TABLE AB_US_2020 (
	id integer not null primary key,
	name varchar(225) not null,
	host_id integer not null,
	host_name varchar(35),
	neighbourhood_group varchar(35),
	neighbourhood varchar(35),
	latitude numeric(8,5),
	longitude numeric(9,5),
	room_type varchar(35) not null,
	price integer not null,
	minimum_nights integer not null,
	number_of_reviews integer not null,
	last_review date,
	reviews_per_month integer not null,
	calculated_host_listings_count integer not null,
	availability_365 integer not null,
	city varchar(35));